/**
 * Seed catalogue. Part numbers follow real manufacturer formats so that the
 * part-number search behaves the way it will with the customer's own data.
 * `specs` are [label_sq, label_en, value_sq, value_en] tuples.
 */

export const products = [
  /* ------------------------------------------------- automation & control */
  {
    part_number: '6ES7214-1AG40-0XB0', brand: 'siemens', category: 'automatizim',
    name_sq: 'SIMATIC S7-1200 CPU 1214C DC/DC/DC',
    name_en: 'SIMATIC S7-1200 CPU 1214C DC/DC/DC',
    summary_sq: 'Njësi qendrore kompakte me 14 hyrje dixhitale, 10 dalje dhe 2 hyrje analoge.',
    summary_en: 'Compact CPU with 14 digital inputs, 10 outputs and 2 analogue inputs.',
    body_sq: 'CPU 1214C është zgjidhja standarde për makineri të vogla dhe të mesme. Programohet me TIA Portal dhe integron portë PROFINET për komunikim me HMI dhe drive. E mbajmë si pjesë kritike rezervë për linjat e klientëve tanë.',
    body_en: 'The CPU 1214C is the standard choice for small and medium machines. Programmed with TIA Portal, it integrates a PROFINET port for communication with HMIs and drives. We hold it as a critical spare for our customers’ lines.',
    availability: 'in_stock', price_eur: 385, is_featured: 1,
    refs: [{ number: '6ES7 214-1AG40-0XB0' }, { number: '6ES72141AG400XB0' }],
    specs: [
      ['Ushqimi', 'Supply voltage', '24 V DC', '24 V DC'],
      ['Hyrje dixhitale', 'Digital inputs', '14 × 24 V DC', '14 × 24 V DC'],
      ['Dalje dixhitale', 'Digital outputs', '10 × 24 V DC, 0.5 A', '10 × 24 V DC, 0.5 A'],
      ['Hyrje analoge', 'Analogue inputs', '2 × 0–10 V', '2 × 0–10 V'],
      ['Memorje pune', 'Work memory', '100 KB', '100 KB'],
      ['Komunikimi', 'Communication', 'PROFINET IO', 'PROFINET IO'],
    ],
  },
  {
    part_number: '6AV2123-2GB03-0AX0', brand: 'siemens', category: 'automatizim',
    name_sq: 'SIMATIC HMI KTP700 Basic, ekran 7"',
    name_en: 'SIMATIC HMI KTP700 Basic, 7" panel',
    summary_sq: 'Panel operatori 7 inç me prekje dhe 8 taste funksioni, ndërfaqe PROFINET.',
    summary_en: '7-inch touch operator panel with 8 function keys and PROFINET interface.',
    body_sq: 'Panel bazë për vizualizim makinerie, i përshtatshëm për zëvendësim të panelëve të vjetër OP/TP. Konfigurohet me WinCC Basic brenda TIA Portal.',
    body_en: 'Entry-level machine visualisation panel, a straightforward replacement for legacy OP/TP panels. Configured with WinCC Basic inside TIA Portal.',
    availability: 'in_stock', price_eur: 520, is_featured: 1,
    refs: [{ number: '6AV2 123-2GB03-0AX0' }, { number: 'KTP700 Basic', kind: 'equivalent' }],
    specs: [
      ['Diagonalja', 'Display size', '7", 800 × 480', '7", 800 × 480'],
      ['Prekja', 'Touch', 'Rezistive', 'Resistive'],
      ['Taste funksioni', 'Function keys', '8', '8'],
      ['Ndërfaqja', 'Interface', 'PROFINET (RJ45)', 'PROFINET (RJ45)'],
      ['Shkalla e mbrojtjes', 'Protection', 'IP65 (përpara)', 'IP65 (front)'],
    ],
  },
  {
    part_number: '750104', brand: 'pilz', category: 'automatizim',
    name_sq: 'PNOZ s4 rele sigurie 24 V DC',
    name_en: 'PNOZ s4 safety relay 24 V DC',
    summary_sq: 'Rele sigurie me 3 kontakte sigurie dhe 1 ndihmës, për ndalim emergjence dhe mbrojtëse.',
    summary_en: 'Safety relay with 3 safety contacts and 1 auxiliary, for E-stop and guard monitoring.',
    body_sq: 'Përdoret për monitorim të butonave të emergjencës, dyerve mbrojtëse dhe barrierave. Arrin PL e sipas EN ISO 13849-1 kur lidhet dykanalësh.',
    body_en: 'Used for monitoring E-stop buttons, safety gates and light curtains. Achieves PL e to EN ISO 13849-1 in dual-channel configuration.',
    availability: 'in_stock', price_eur: 195,
    specs: [
      ['Ushqimi', 'Supply voltage', '24 V DC', '24 V DC'],
      ['Kontakte sigurie', 'Safety contacts', '3 N/O', '3 N/O'],
      ['Kontakte ndihmëse', 'Auxiliary contacts', '1 N/C', '1 N/C'],
      ['Niveli i performancës', 'Performance level', 'PL e / Cat. 4', 'PL e / Cat. 4'],
      ['Gjerësia', 'Width', '22.5 mm', '22.5 mm'],
    ],
  },
  {
    part_number: 'AZ 16-02ZVRK-M20', brand: 'schmersal', category: 'automatizim',
    name_sq: 'Çelës sigurie me aktivizues të ndarë AZ 16',
    name_en: 'AZ 16 safety interlock switch with separate actuator',
    summary_sq: 'Çelës për monitorim dyersh mbrojtëse me trup termoplastik dhe kontakte të detyruara.',
    summary_en: 'Guard door monitoring switch with thermoplastic body and positively driven contacts.',
    availability: 'lead_time', lead_time_days: 7, price_eur: 68,
    specs: [
      ['Kontaktet', 'Contacts', '2 N/C + 1 N/O', '2 N/C + 1 N/O'],
      ['Mbrojtja', 'Protection', 'IP67', 'IP67'],
      ['Lidhja', 'Connection', 'M20 presakabllo', 'M20 cable gland'],
    ],
  },

  /* -------------------------------------------------------- motors & drives */
  {
    part_number: '6SL3210-5BE21-5UV0', brand: 'siemens', category: 'motore-drive',
    name_sq: 'SINAMICS V20 inverter 1.5 kW, 3AC 400 V',
    name_en: 'SINAMICS V20 inverter 1.5 kW, 3AC 400 V',
    summary_sq: 'Inverter frekuence kompakt për pompa, ventilatorë dhe transportues.',
    summary_en: 'Compact frequency inverter for pumps, fans and conveyors.',
    body_sq: 'V20 ofron vënie në punë të shpejtë me menu bazë dhe funksion kursimi energjie. Ne e konfigurojmë dhe parametrizojmë në vend sipas aplikimit tuaj.',
    body_en: 'The V20 offers fast commissioning through its basic menu plus an energy-saving function. We configure and parameterise it on site for your application.',
    availability: 'in_stock', price_eur: 340, is_featured: 1,
    refs: [{ number: '6SL3210 5BE21 5UV0' }],
    specs: [
      ['Fuqia', 'Rated power', '1.5 kW', '1.5 kW'],
      ['Tensioni', 'Supply', '380–480 V, 3AC', '380–480 V, 3AC'],
      ['Rryma dalëse', 'Output current', '4.1 A', '4.1 A'],
      ['Filtri', 'Filter', 'I integruar klasi A', 'Integrated class A'],
      ['Mbrojtja', 'Protection', 'IP20', 'IP20'],
    ],
  },
  {
    part_number: 'ATV320U15N4B', brand: 'schneider-electric', category: 'motore-drive',
    name_sq: 'Altivar Machine ATV320 1.5 kW, 400 V',
    name_en: 'Altivar Machine ATV320 1.5 kW, 400 V',
    summary_sq: 'Inverter me funksione sigurie STO të integruara për makineri.',
    summary_en: 'Machine inverter with integrated STO safety function.',
    availability: 'in_stock', price_eur: 395,
    refs: [{ number: 'ATV320U15N4' }],
    specs: [
      ['Fuqia', 'Rated power', '1.5 kW', '1.5 kW'],
      ['Tensioni', 'Supply', '380–500 V, 3AC', '380–500 V, 3AC'],
      ['Siguria', 'Safety', 'STO, SIL3', 'STO, SIL3'],
      ['Formati', 'Format', 'Book (compact)', 'Book (compact)'],
    ],
  },
  {
    part_number: 'ACS580-01-05A6-4', brand: 'abb', category: 'motore-drive',
    name_sq: 'ACS580 inverter 2.2 kW, 400 V',
    name_en: 'ACS580 inverter 2.2 kW, 400 V',
    summary_sq: 'Drive i përgjithshëm me çok DC dhe asistentë vënieje në punë.',
    summary_en: 'General-purpose drive with built-in DC choke and start-up assistants.',
    availability: 'lead_time', lead_time_days: 10, price_eur: 460,
    specs: [
      ['Fuqia', 'Rated power', '2.2 kW', '2.2 kW'],
      ['Rryma', 'Rated current', '5.6 A', '5.6 A'],
      ['Mbrojtja', 'Protection', 'IP21', 'IP21'],
    ],
  },
  {
    part_number: 'FR-E840-0016EPB-60', brand: 'mitsubishi-electric', category: 'motore-drive',
    name_sq: 'Inverter FR-E800 0.75 kW, 400 V',
    name_en: 'FR-E800 inverter 0.75 kW, 400 V',
    summary_sq: 'Inverter kompakt me diagnostikim parashikues dhe Ethernet opsional.',
    summary_en: 'Compact inverter with predictive diagnostics and optional Ethernet.',
    availability: 'on_request', price_eur: null,
    specs: [
      ['Fuqia', 'Rated power', '0.75 kW', '0.75 kW'],
      ['Tensioni', 'Supply', '380–480 V, 3AC', '380–480 V, 3AC'],
    ],
  },
  {
    part_number: 'W22-100L-4P-3', brand: 'weg', category: 'motore-drive',
    name_sq: 'Motor trefazor W22 3 kW, 4 pole, IE3',
    name_en: 'W22 three-phase motor 3 kW, 4-pole, IE3',
    summary_sq: 'Motor asinkron me efiçencë premium, flanxhë B3, kornizë 100L.',
    summary_en: 'Premium-efficiency induction motor, B3 foot mount, 100L frame.',
    availability: 'lead_time', lead_time_days: 14, price_eur: 415,
    specs: [
      ['Fuqia', 'Rated power', '3 kW', '3 kW'],
      ['Shpejtësia', 'Speed', '1440 rpm', '1440 rpm'],
      ['Efiçenca', 'Efficiency class', 'IE3', 'IE3'],
      ['Korniza', 'Frame', '100L', '100L'],
      ['Mbrojtja', 'Protection', 'IP55', 'IP55'],
    ],
  },

  /* --------------------------------------------------------------- electrical */
  {
    part_number: '3RT2026-1BB40', brand: 'siemens', category: 'elektrike',
    name_sq: 'Kontaktor SIRIUS 11 kW, bobinë 24 V DC',
    name_en: 'SIRIUS contactor 11 kW, 24 V DC coil',
    summary_sq: 'Kontaktor 3-polësh AC-3 25 A me kontakt ndihmës 1 N/O.',
    summary_en: '3-pole AC-3 25 A contactor with 1 N/O auxiliary contact.',
    body_sq: 'Kontaktori më i përdorur në panelet e makinerive. Mbahet gjithmonë në stok bashkë me bllokun e kontakteve ndihmëse dhe mbrojtësin termik përkatës.',
    body_en: 'The most commonly used contactor in machine panels. Always held in stock together with matching auxiliary contact blocks and overload relays.',
    availability: 'in_stock', price_eur: 46, is_featured: 1,
    refs: [{ number: '3RT2026 1BB40' }, { number: '3RT20261BB40' }],
    specs: [
      ['Fuqia AC-3', 'AC-3 power', '11 kW / 400 V', '11 kW / 400 V'],
      ['Rryma AC-3', 'AC-3 current', '25 A', '25 A'],
      ['Bobina', 'Coil voltage', '24 V DC', '24 V DC'],
      ['Kontakte ndihmëse', 'Auxiliary', '1 N/O', '1 N/O'],
      ['Madhësia', 'Size', 'S0', 'S0'],
    ],
  },
  {
    part_number: 'LC1D18M7', brand: 'schneider-electric', category: 'elektrike',
    name_sq: 'Kontaktor TeSys D 7.5 kW, bobinë 220 V AC',
    name_en: 'TeSys D contactor 7.5 kW, 220 V AC coil',
    summary_sq: 'Kontaktor 3-polësh 18 A me kontakte ndihmëse 1 N/O + 1 N/C.',
    summary_en: '3-pole 18 A contactor with 1 N/O + 1 N/C auxiliary contacts.',
    availability: 'in_stock', price_eur: 38,
    refs: [{ number: 'LC1-D18M7' }],
    specs: [
      ['Rryma AC-3', 'AC-3 current', '18 A', '18 A'],
      ['Bobina', 'Coil voltage', '220 V AC, 50/60 Hz', '220 V AC, 50/60 Hz'],
      ['Kontakte ndihmëse', 'Auxiliary', '1 N/O + 1 N/C', '1 N/O + 1 N/C'],
    ],
  },
  {
    part_number: 'AF16-30-10-13', brand: 'abb', category: 'elektrike',
    name_sq: 'Kontaktor AF16 7.5 kW, bobinë 100–250 V AC/DC',
    name_en: 'AF16 contactor 7.5 kW, 100–250 V AC/DC coil',
    summary_sq: 'Kontaktor me bobinë elektronike me gamë të gjerë tensioni.',
    summary_en: 'Contactor with wide-range electronic coil.',
    availability: 'in_stock', price_eur: 42,
    refs: [{ number: '1SBL177001R1310', kind: 'oem' }],
    specs: [
      ['Rryma AC-3', 'AC-3 current', '18 A', '18 A'],
      ['Bobina', 'Coil', '100–250 V AC/DC', '100–250 V AC/DC'],
    ],
  },
  {
    part_number: 'PKZM0-6.3', brand: 'eaton', category: 'elektrike',
    name_sq: 'Çelës mbrojtës motorik 4–6.3 A',
    name_en: 'Motor protective circuit breaker 4–6.3 A',
    summary_sq: 'Mbrojtje termike dhe magnetike për motorë deri në 2.2 kW.',
    summary_en: 'Thermal and magnetic protection for motors up to 2.2 kW.',
    availability: 'in_stock', price_eur: 54,
    specs: [
      ['Gama e rregullimit', 'Setting range', '4–6.3 A', '4–6.3 A'],
      ['Kapaciteti i ndërprerjes', 'Breaking capacity', '150 kA @ 400 V', '150 kA @ 400 V'],
    ],
  },
  {
    part_number: '2866750', brand: 'phoenix-contact', category: 'elektrike',
    name_sq: 'QUINT POWER ushqyes 24 V DC / 10 A',
    name_en: 'QUINT POWER supply 24 V DC / 10 A',
    summary_sq: 'Ushqyes primar i kaluar me rezervë fuqie SFB për shkrepjen e siguresave.',
    summary_en: 'Primary-switched power supply with SFB reserve for reliable fuse tripping.',
    body_sq: 'Ushqyesi QUINT me teknologji SFB jep deri në 6 herë rrymën nominale për 12 ms, çka siguron shkrepjen e sigurt të mbrojtjeve në degët e ngarkesës. I rekomanduar për panelet ku besueshmëria e 24 V është kritike.',
    body_en: 'The QUINT supply with SFB technology delivers up to six times nominal current for 12 ms, ensuring reliable tripping of downstream protective devices. Recommended where 24 V reliability is critical.',
    availability: 'in_stock', price_eur: 268, is_featured: 1,
    specs: [
      ['Hyrja', 'Input', '100–240 V AC', '100–240 V AC'],
      ['Dalja', 'Output', '24 V DC / 10 A', '24 V DC / 10 A'],
      ['Rezerva', 'Power boost', 'SFB 6× për 12 ms', 'SFB 6× for 12 ms'],
      ['Efiçenca', 'Efficiency', '94 %', '94 %'],
    ],
  },
  {
    part_number: '3044076', brand: 'phoenix-contact', category: 'elektrike',
    name_sq: 'Klemë kalimi UT 2.5, gri',
    name_en: 'UT 2.5 feed-through terminal block, grey',
    summary_sq: 'Klemë me vidë për prerje 0.14–4 mm², montim në shinë DIN 35.',
    summary_en: 'Screw terminal for 0.14–4 mm² conductors, DIN 35 rail mount.',
    availability: 'in_stock', price_eur: 1.15,
    specs: [
      ['Prerja', 'Cross-section', '0.14–4 mm²', '0.14–4 mm²'],
      ['Rryma nominale', 'Rated current', '24 A', '24 A'],
      ['Gjerësia', 'Width', '5.2 mm', '5.2 mm'],
    ],
  },
  {
    part_number: '1010000000', brand: 'weidmuller', category: 'elektrike',
    name_sq: 'Klemë WDU 2.5 me vidë',
    name_en: 'WDU 2.5 screw terminal',
    summary_sq: 'Klemë standarde kalimi për panele komandimi.',
    summary_en: 'Standard feed-through terminal for control panels.',
    availability: 'in_stock', price_eur: 1.05,
    specs: [
      ['Prerja', 'Cross-section', '0.5–4 mm²', '0.5–4 mm²'],
      ['Rryma nominale', 'Rated current', '24 A', '24 A'],
    ],
  },
  {
    part_number: 'MY2N-GS 24VDC', brand: 'omron', category: 'elektrike',
    name_sq: 'Rele ndihmëse MY2N 2 kontakte, 24 V DC',
    name_en: 'MY2N miniature relay 2 CO, 24 V DC',
    summary_sq: 'Rele me LED treguese dhe bazë të përshtatshme PYF08A.',
    summary_en: 'Relay with indicator LED and matching PYF08A socket.',
    availability: 'in_stock', price_eur: 7.4,
    refs: [{ number: 'MY2N-GS-24VDC' }, { number: 'MY2NGS24VDC' }],
    specs: [
      ['Kontaktet', 'Contacts', '2 CO (DPDT)', '2 CO (DPDT)'],
      ['Rryma e kontaktit', 'Contact rating', '5 A / 250 V AC', '5 A / 250 V AC'],
      ['Bobina', 'Coil', '24 V DC', '24 V DC'],
    ],
  },
  {
    part_number: 'XB4BA31', brand: 'schneider-electric', category: 'elektrike',
    name_sq: 'Buton Harmony Ø22 i gjelbër, 1 N/O',
    name_en: 'Harmony Ø22 green pushbutton, 1 N/O',
    summary_sq: 'Buton metalik i sheshtë me kontakt të vetëm normalisht të hapur.',
    summary_en: 'Flush metal pushbutton with single normally-open contact.',
    availability: 'in_stock', price_eur: 12.8,
    specs: [
      ['Diametri', 'Diameter', 'Ø22 mm', 'Ø22 mm'],
      ['Kontaktet', 'Contacts', '1 N/O', '1 N/O'],
      ['Materiali', 'Bezel', 'Metal', 'Metal'],
    ],
  },

  /* ------------------------------------------------------------------ sensors */
  {
    part_number: 'E3Z-D62', brand: 'omron', category: 'sensore',
    name_sq: 'Sensor fotoelektrik difuz, 1 m, PNP',
    name_en: 'Diffuse photoelectric sensor, 1 m, PNP',
    summary_sq: 'Sensor kompakt me rregullim ndjeshmërie dhe kabllo 2 m.',
    summary_en: 'Compact sensor with sensitivity adjustment and 2 m cable.',
    availability: 'in_stock', price_eur: 58,
    refs: [{ number: 'E3Z D62' }],
    specs: [
      ['Distanca', 'Sensing distance', '1 m', '1 m'],
      ['Dalja', 'Output', 'PNP N/O + N/C', 'PNP N/O + N/C'],
      ['Ushqimi', 'Supply', '12–24 V DC', '12–24 V DC'],
      ['Mbrojtja', 'Protection', 'IP67', 'IP67'],
    ],
  },
  {
    part_number: 'WL12-2P430', brand: 'sick', category: 'sensore',
    name_sq: 'Sensor fotoelektrik reflektues W12-2',
    name_en: 'W12-2 retro-reflective photoelectric sensor',
    summary_sq: 'Sensor me rreze të kuqe dhe distancë deri 5 m me reflektor.',
    summary_en: 'Red-light sensor with up to 5 m range using a reflector.',
    availability: 'lead_time', lead_time_days: 5, price_eur: 96,
    specs: [
      ['Distanca', 'Sensing range', '0–5 m', '0–5 m'],
      ['Dalja', 'Output', 'PNP', 'PNP'],
      ['Lidhja', 'Connection', 'M12, 4-pin', 'M12, 4-pin'],
    ],
  },
  {
    part_number: 'BES 516-300-S166-S4-D', brand: 'balluff', category: 'sensore',
    name_sq: 'Sensor induktiv M12, 4 mm, PNP',
    name_en: 'M12 inductive sensor, 4 mm, PNP',
    summary_sq: 'Sensor afërsie i mbrojtur me lidhje konektor M12.',
    summary_en: 'Shielded proximity sensor with M12 connector.',
    availability: 'in_stock', price_eur: 44,
    refs: [{ number: 'BES516-300-S166-S4-D' }],
    specs: [
      ['Distanca', 'Switching distance', '4 mm', '4 mm'],
      ['Dalja', 'Output', 'PNP N/O', 'PNP N/O'],
      ['Mbrojtja', 'Protection', 'IP67', 'IP67'],
    ],
  },
  {
    part_number: 'IFS204', brand: 'ifm', category: 'sensore',
    name_sq: 'Sensor induktiv M12 i lidhur me konektor',
    name_en: 'M12 inductive sensor with connector',
    summary_sq: 'Sensor afërsie 4 mm me trup inoks dhe LED statusi.',
    summary_en: '4 mm proximity sensor with stainless body and status LED.',
    availability: 'in_stock', price_eur: 39,
    specs: [
      ['Distanca', 'Switching distance', '4 mm', '4 mm'],
      ['Ushqimi', 'Supply', '10–30 V DC', '10–30 V DC'],
    ],
  },

  /* --------------------------------------------------------------- pneumatics */
  {
    part_number: 'DSBC-32-100-PPVA-N3', brand: 'festo', category: 'pneumatike',
    name_sq: 'Cilindër ISO 15552 Ø32, goditje 100 mm',
    name_en: 'ISO 15552 cylinder Ø32, 100 mm stroke',
    summary_sq: 'Cilindër me veprim të dyfishtë me amortizim të vetërregullueshëm PPV.',
    summary_en: 'Double-acting cylinder with self-adjusting PPV cushioning.',
    body_sq: 'Cilindri standard ISO për automatizim makinerie. Ofrojmë edhe versionet me sensor pozicioni dhe grupet e riparimit me guarnicione origjinale.',
    body_en: 'The standard ISO cylinder for machine automation. We also supply position-sensing variants and original seal repair kits.',
    availability: 'in_stock', price_eur: 132, is_featured: 1,
    refs: [{ number: 'DSBC-32-100-PPVA-N3', kind: 'oem' }, { number: '1383571', kind: 'oem' }],
    specs: [
      ['Diametri i pistonit', 'Piston diameter', '32 mm', '32 mm'],
      ['Goditja', 'Stroke', '100 mm', '100 mm'],
      ['Presioni', 'Operating pressure', '0.4–12 bar', '0.4–12 bar'],
      ['Amortizimi', 'Cushioning', 'PPV vetërregullues', 'Self-adjusting PPV'],
      ['Lidhjet', 'Ports', 'G1/8', 'G1/8'],
    ],
  },
  {
    part_number: 'VUVG-L10-M52-MT-M5-1P3', brand: 'festo', category: 'pneumatike',
    name_sq: 'Elektrovalvulë 5/2 monostabile, M5',
    name_en: '5/2 single-solenoid valve, M5',
    summary_sq: 'Valvulë kompakte për montim individual ose në ishull valvulash.',
    summary_en: 'Compact valve for individual or valve-terminal mounting.',
    availability: 'in_stock', price_eur: 74,
    specs: [
      ['Funksioni', 'Function', '5/2 monostabile', '5/2 single solenoid'],
      ['Rrjedhja', 'Flow rate', '390 l/min', '390 l/min'],
      ['Lidhjet', 'Ports', 'M5', 'M5'],
    ],
  },
  {
    part_number: 'SY5120-5LZD-01', brand: 'smc', category: 'pneumatike',
    name_sq: 'Elektrovalvulë SY5000 5/2, 24 V DC',
    name_en: 'SY5000 5/2 solenoid valve, 24 V DC',
    summary_sq: 'Valvulë me lidhje G1/8 dhe konektor L-plug me LED.',
    summary_en: 'Valve with G1/8 ports and L-plug connector with LED.',
    availability: 'in_stock', price_eur: 62,
    refs: [{ number: 'SY5120 5LZD 01' }],
    specs: [
      ['Funksioni', 'Function', '5/2 monostabile', '5/2 single solenoid'],
      ['Bobina', 'Coil', '24 V DC, 1 W', '24 V DC, 1 W'],
      ['Lidhjet', 'Ports', 'G1/8', 'G1/8'],
    ],
  },
  {
    part_number: 'AW30-03BG-B', brand: 'smc', category: 'pneumatike',
    name_sq: 'Filtër-rregullator G3/8 me manometër',
    name_en: 'G3/8 filter regulator with gauge',
    summary_sq: 'Njësi përgatitjeje ajri me element 5 µm dhe kullim gjysmë-automatik.',
    summary_en: 'Air preparation unit with 5 µm element and semi-automatic drain.',
    availability: 'in_stock', price_eur: 78,
    specs: [
      ['Lidhja', 'Port size', 'G3/8', 'G3/8'],
      ['Filtrimi', 'Filtration', '5 µm', '5 µm'],
      ['Gama e rregullimit', 'Regulating range', '0.05–0.85 MPa', '0.05–0.85 MPa'],
    ],
  },
  {
    part_number: 'MS6-LFR-1/2-D7-CRM-AS', brand: 'festo', category: 'pneumatike',
    name_sq: 'Njësi filtër-rregullator MS6, G1/2',
    name_en: 'MS6 filter regulator unit, G1/2',
    summary_sq: 'Përgatitje ajri për linja me konsum të lartë, me kullim automatik.',
    summary_en: 'Air preparation for high-consumption lines, with automatic drain.',
    availability: 'lead_time', lead_time_days: 7, price_eur: 186,
    specs: [
      ['Lidhja', 'Port size', 'G1/2', 'G1/2'],
      ['Filtrimi', 'Filtration', '40 µm', '40 µm'],
      ['Rrjedhja', 'Flow', '5200 l/min', '5200 l/min'],
    ],
  },

  /* --------------------------------------------------------------- hydraulics */
  {
    part_number: '4WE6D6X/EG24N9K4', brand: 'bosch-rexroth', category: 'hidraulike',
    name_sq: 'Valvulë drejtuese 4/3, NG6, 24 V DC',
    name_en: '4/3 directional valve, NG6, 24 V DC',
    summary_sq: 'Valvulë e komanduar elektrikisht me qendër tandem, madhësia 6.',
    summary_en: 'Solenoid-operated valve with tandem centre, size 6.',
    body_sq: 'Valvula më e përhapur NG6 për blloqe hidraulike industriale. Furnizojmë edhe bobinat rezervë dhe grupet e guarnicioneve.',
    body_en: 'The most widespread NG6 valve for industrial hydraulic manifolds. We also supply replacement coils and seal kits.',
    availability: 'lead_time', lead_time_days: 12, price_eur: 285,
    refs: [{ number: 'R900561276', kind: 'oem' }, { number: '4WE 6 D6X/EG24N9K4' }],
    specs: [
      ['Madhësia', 'Size', 'NG6 / CETOP 3', 'NG6 / CETOP 3'],
      ['Presioni maksimal', 'Max pressure', '350 bar', '350 bar'],
      ['Rrjedhja', 'Max flow', '80 l/min', '80 l/min'],
      ['Bobina', 'Solenoid', '24 V DC', '24 V DC'],
    ],
  },
  {
    part_number: '0160D010BN4HC', brand: 'hydac', category: 'hidraulike',
    name_sq: 'Element filtri 0160 D 010 BN4HC',
    name_en: 'Filter element 0160 D 010 BN4HC',
    summary_sq: 'Element presioni 10 µm për filtra në linjë, ndërtim Betamicron.',
    summary_en: '10 µm pressure line element, Betamicron construction.',
    availability: 'in_stock', price_eur: 92,
    refs: [{ number: '0160 D 010 BN4HC' }, { number: '1263061', kind: 'oem' }],
    specs: [
      ['Filtrimi', 'Filtration rating', '10 µm absolute', '10 µm absolute'],
      ['Diferenca e presionit', 'Collapse rating', '210 bar', '210 bar'],
    ],
  },
  {
    part_number: '932670Q', brand: 'parker', category: 'hidraulike',
    name_sq: 'Element filtri kthimi 10 µm',
    name_en: 'Return-line filter element 10 µm',
    summary_sq: 'Element mikrofibre për filtra kthimi në rezervuar.',
    summary_en: 'Microfibre element for tank-mounted return filters.',
    availability: 'lead_time', lead_time_days: 9, price_eur: 64,
    specs: [
      ['Filtrimi', 'Filtration rating', '10 µm', '10 µm'],
      ['Materiali', 'Media', 'Mikrofibër', 'Microfibre'],
    ],
  },

  /* -------------------------------------------------------------- mechanical */
  {
    part_number: '6205-2RSH', brand: 'skf', category: 'mekanike',
    name_sq: 'Kushinetë sferike 6205-2RSH, 25×52×15',
    name_en: 'Deep groove ball bearing 6205-2RSH, 25×52×15',
    summary_sq: 'Kushinetë me dy guarnicione gome, e mbushur me graso.',
    summary_en: 'Bearing with two contact seals, grease filled for life.',
    body_sq: 'Një nga kushinetat më të kërkuara në industri. E mbajmë në stok së bashku me masat fqinje 6204, 6206 dhe 6208 për ndërhyrje të menjëhershme.',
    body_en: 'One of the most requested bearings in industry. Held in stock alongside neighbouring sizes 6204, 6206 and 6208 for immediate intervention.',
    availability: 'in_stock', price_eur: 9.8, is_featured: 1,
    refs: [{ number: '6205-2RS1' }, { number: '6205 2RSH' }, { number: '62052RS' }],
    specs: [
      ['Diametri i brendshëm', 'Bore', '25 mm', '25 mm'],
      ['Diametri i jashtëm', 'Outside diameter', '52 mm', '52 mm'],
      ['Gjerësia', 'Width', '15 mm', '15 mm'],
      ['Ngarkesa dinamike', 'Dynamic load rating', '14.8 kN', '14.8 kN'],
      ['Shpejtësia maksimale', 'Limiting speed', '7500 rpm', '7500 rpm'],
    ],
  },
  {
    part_number: '22215 EK', brand: 'skf', category: 'mekanike',
    name_sq: 'Kushinetë sferike me dy rreshta 22215 EK',
    name_en: 'Spherical roller bearing 22215 EK',
    summary_sq: 'Kushinetë me vrimë konike 1:12 për montim me buçelë.',
    summary_en: 'Bearing with 1:12 tapered bore for adapter sleeve mounting.',
    availability: 'lead_time', lead_time_days: 6, price_eur: 148,
    refs: [{ number: '22215EK' }],
    specs: [
      ['Vrima', 'Bore', '75 mm', '75 mm'],
      ['Diametri i jashtëm', 'Outside diameter', '130 mm', '130 mm'],
      ['Gjerësia', 'Width', '31 mm', '31 mm'],
    ],
  },
  {
    part_number: '6206-2Z', brand: 'fag', category: 'mekanike',
    name_sq: 'Kushinetë sferike 6206-2Z, 30×62×16',
    name_en: 'Deep groove ball bearing 6206-2Z, 30×62×16',
    summary_sq: 'Kushinetë me dy kapakë metalikë për shpejtësi të larta.',
    summary_en: 'Bearing with two metal shields for higher speeds.',
    availability: 'in_stock', price_eur: 11.2,
    refs: [{ number: '6206 2Z' }, { number: '62062Z' }],
    specs: [
      ['Vrima', 'Bore', '30 mm', '30 mm'],
      ['Diametri i jashtëm', 'Outside diameter', '62 mm', '62 mm'],
      ['Gjerësia', 'Width', '16 mm', '16 mm'],
    ],
  },
  {
    part_number: 'SNL 517-615', brand: 'skf', category: 'mekanike',
    name_sq: 'Njësi mbajtëse e ndarë SNL 517-615',
    name_en: 'Split plummer block housing SNL 517-615',
    summary_sq: 'Trup gize i ndarë për kushineta me buçelë, boshte 75 mm.',
    summary_en: 'Split cast-iron housing for adapter-mounted bearings, 75 mm shafts.',
    availability: 'on_request', price_eur: null,
    specs: [
      ['Boshti', 'Shaft diameter', '75 mm', '75 mm'],
      ['Materiali', 'Material', 'Gizë gri', 'Grey cast iron'],
    ],
  },
  {
    part_number: '8MGT-1600-30', brand: 'gates', category: 'mekanike',
    name_sq: 'Rrip Poly Chain GT Carbon 8M-1600-30',
    name_en: 'Poly Chain GT Carbon belt 8M-1600-30',
    summary_sq: 'Rrip sinkron me kord karboni për transmisione me moment të lartë.',
    summary_en: 'Synchronous belt with carbon cord for high-torque drives.',
    availability: 'lead_time', lead_time_days: 8, price_eur: 168,
    refs: [{ number: '8MGT 1600 30' }],
    specs: [
      ['Hapi', 'Pitch', '8 mm', '8 mm'],
      ['Gjatësia', 'Length', '1600 mm', '1600 mm'],
      ['Gjerësia', 'Width', '30 mm', '30 mm'],
    ],
  },
  {
    part_number: 'XPZ 1250', brand: 'gates', category: 'mekanike',
    name_sq: 'Rrip trapezoidal i dhëmbëzuar XPZ 1250',
    name_en: 'XPZ 1250 cogged V-belt',
    summary_sq: 'Rrip me profil të ngushtë për transmisione ventilatorësh e pompash.',
    summary_en: 'Narrow-section belt for fan and pump drives.',
    availability: 'in_stock', price_eur: 14.5,
    specs: [
      ['Profili', 'Section', 'XPZ / 3VX', 'XPZ / 3VX'],
      ['Gjatësia efektive', 'Effective length', '1250 mm', '1250 mm'],
    ],
  },

  /* ---------------------------------------------------------- cable & panels */
  {
    part_number: '1119206', brand: 'lapp', category: 'kabllo',
    name_sq: 'ÖLFLEX CLASSIC 110 4G1.5 mm²',
    name_en: 'ÖLFLEX CLASSIC 110 4G1.5 mm²',
    summary_sq: 'Kabllo kontrolli fleksibël PVC me përcjellës tokëzimi, gri.',
    summary_en: 'Flexible PVC control cable with earth conductor, grey.',
    availability: 'in_stock', price_eur: 2.35, unit: 'm',
    specs: [
      ['Përcjellësit', 'Cores', '4G1.5 mm²', '4G1.5 mm²'],
      ['Tensioni nominal', 'Rated voltage', '300/500 V', '300/500 V'],
      ['Temperatura', 'Temperature range', '−5 … +80 °C', '−5 … +80 °C'],
    ],
  },
  {
    part_number: 'CF130.07.04', brand: 'igus', category: 'kabllo',
    name_sq: 'Kabllo chainflex CF130 4G0.75 për zinxhir',
    name_en: 'chainflex CF130 4G0.75 drag-chain cable',
    summary_sq: 'Kabllo kontrolli për lëvizje të vazhdueshme në zinxhir energjie.',
    summary_en: 'Control cable for continuous motion in energy chains.',
    availability: 'lead_time', lead_time_days: 10, price_eur: 5.9, unit: 'm',
    specs: [
      ['Përcjellësit', 'Cores', '4G0.75 mm²', '4G0.75 mm²'],
      ['Rrezja e përkuljes', 'Bend radius', '7.5 × Ø', '7.5 × Ø'],
      ['Cikle', 'Rated cycles', '5 milionë', '5 million'],
    ],
  },
  {
    part_number: 'SK 3238.100', brand: 'rittal', category: 'panele',
    name_sq: 'Ventilator me filtër SK 3238, 105 m³/h',
    name_en: 'SK 3238 filter fan, 105 m³/h',
    summary_sq: 'Ventilator paneli 230 V me filtër të zëvendësueshëm, prerje 148×148.',
    summary_en: '230 V panel fan with replaceable filter mat, 148×148 cut-out.',
    availability: 'in_stock', price_eur: 88,
    refs: [{ number: '3238100' }, { number: 'SK3238.100' }],
    specs: [
      ['Rrjedhja e ajrit', 'Air flow', '105 m³/h', '105 m³/h'],
      ['Tensioni', 'Voltage', '230 V, 50/60 Hz', '230 V, 50/60 Hz'],
      ['Prerja', 'Cut-out', '148 × 148 mm', '148 × 148 mm'],
      ['Mbrojtja', 'Protection', 'IP54', 'IP54'],
    ],
  },

  /* -------------------------------------------------------------- consumables */
  {
    part_number: 'LOCTITE 243 50ML', brand: 'loctite', category: 'konsumabile',
    name_sq: 'LOCTITE 243 mbyllës filetash, forcë mesatare, 50 ml',
    name_en: 'LOCTITE 243 threadlocker, medium strength, 50 ml',
    summary_sq: 'Ngjitës anaerobik për siguri filetash, toleron sipërfaqe të vajosura.',
    summary_en: 'Anaerobic threadlocker tolerant of lightly oiled surfaces.',
    body_sq: 'Produkti standard për sigurimin e bulonave në makineri me vibrim. Aplikohet lehtë dhe lejon çmontim me vegla dore.',
    body_en: 'The standard product for securing bolts on vibrating machinery. Easy to apply and removable with hand tools.',
    availability: 'in_stock', price_eur: 22.5, is_featured: 1,
    refs: [{ number: '1335884', kind: 'oem' }],
    specs: [
      ['Forca', 'Strength', 'Mesatare', 'Medium'],
      ['Temperatura', 'Temperature range', '−55 … +180 °C', '−55 … +180 °C'],
      ['Filetat', 'Thread size', 'deri M36', 'up to M36'],
      ['Vëllimi', 'Volume', '50 ml', '50 ml'],
    ],
  },
  {
    part_number: 'LGMT 2/1', brand: 'skf', category: 'konsumabile',
    name_sq: 'Graso SKF LGMT 2, 1 kg',
    name_en: 'SKF LGMT 2 grease, 1 kg',
    summary_sq: 'Graso litiumi për përdorim të përgjithshëm industrial.',
    summary_en: 'General-purpose industrial lithium grease.',
    availability: 'in_stock', price_eur: 18.9,
    specs: [
      ['Klasa NLGI', 'NLGI grade', '2', '2'],
      ['Temperatura', 'Temperature range', '−30 … +120 °C', '−30 … +120 °C'],
      ['Paketimi', 'Pack size', '1 kg', '1 kg'],
    ],
  },
  {
    part_number: 'KLUEBERSYNTH UH1 6-460', brand: 'klueber', category: 'konsumabile',
    name_sq: 'Vaj sintetik për reduktorë, cilësi ushqimore H1, 1 l',
    name_en: 'Food-grade H1 synthetic gear oil, 1 l',
    summary_sq: 'Lubrifikant NSF H1 për reduktorë në industrinë ushqimore.',
    summary_en: 'NSF H1 lubricant for gearboxes in food production.',
    availability: 'lead_time', lead_time_days: 12, price_eur: 46,
    specs: [
      ['Viskoziteti', 'Viscosity', 'ISO VG 460', 'ISO VG 460'],
      ['Çertifikimi', 'Approval', 'NSF H1', 'NSF H1'],
    ],
  },
];
