/** Seed content: technical services. `points` are [text_sq, text_en] tuples. */

export const services = [
  {
    slug: 'diagnostikim-elektrik', icon: 'bolt', sort: 10,
    title_sq: 'Diagnostikim dhe riparim elektrik',
    title_en: 'Electrical diagnostics & repair',
    summary_sq: 'Gjetja e shkakut rrënjësor të defekteve elektrike në panele, motorë dhe shpërndarje.',
    summary_en: 'Root-cause diagnosis of electrical faults in panels, motors and distribution.',
    body_sq: 'Kur një linjë ndalon pa shkak të dukshëm, humbja reale nuk është pjesa e prishur — është koha. Ekipi ynë vjen me instrumente matëse, skema dhe përvojë në panele industriale, dhe punon nga simptoma te shkaku: matje tensioni dhe rryme nën ngarkesë, kontroll i mbrojtjeve dhe i lidhjeve, verifikim i qarqeve komanduese dhe i sinjaleve 24 V. Dokumentojmë çdo gjetje dhe ju lëmë një raport me masat korrigjuese dhe pjesët që duhen zëvendësuar.',
    body_en: 'When a line stops for no visible reason, the real loss is not the broken part — it is the time. Our team arrives with measuring instruments, drawings and hands-on experience in industrial panels, and works from symptom to cause: voltage and current measurement under load, checking protective devices and terminations, verifying control circuits and 24 V signalling. Every finding is documented and you receive a report with corrective actions and the parts that need replacing.',
    points: [
      ['Matje me kamerë termike për lidhje të nxehta dhe ngarkesa të pabalancuara', 'Thermal imaging for hot joints and unbalanced loads'],
      ['Kontroll izolimi dhe vazhdimësie në motorë e kabllo fuqie', 'Insulation and continuity testing on motors and power cable'],
      ['Analizë e qarqeve komanduese dhe rindërtim skemash që mungojnë', 'Control circuit analysis and reconstruction of missing drawings'],
      ['Zëvendësim kontaktorësh, releve, mbrojtjeve dhe ushqyesve', 'Replacement of contactors, relays, protection devices and power supplies'],
      ['Rregullim i tokëzimit dhe i mbrojtjes nga mbitensioni', 'Earthing and surge-protection corrections'],
    ],
  },
  {
    slug: 'zgjidhje-automatizimi', icon: 'cpu', sort: 20,
    title_sq: 'Zgjidhje problemesh në automatizim',
    title_en: 'Automation troubleshooting',
    summary_sq: 'Analizë e sistemeve të kontrollit kur makina sillet ndryshe nga ç’duhet.',
    summary_en: 'Analysis of control systems when a machine behaves differently than it should.',
    body_sq: 'Defektet e automatizimit rrallë janë atje ku duken. Ne lexojmë programin, gjurmojmë sinjalet në kohë reale dhe krahasojmë sjelljen e makinës me sekuencën e projektuar. Punojmë me PLC Siemens, Schneider, Omron dhe Mitsubishi, me rrjeta PROFINET, PROFIBUS, Modbus dhe IO-Link, si dhe me sisteme sigurie sipas EN ISO 13849.',
    body_en: 'Automation faults are rarely where they appear to be. We read the program, trace signals live and compare machine behaviour against the designed sequence. We work with Siemens, Schneider, Omron and Mitsubishi PLCs, with PROFINET, PROFIBUS, Modbus and IO-Link networks, and with safety systems to EN ISO 13849.',
    points: [
      ['Gjurmim online i sinjaleve dhe forcim i hyrje-daljeve për izolim defekti', 'Online signal tracing and I/O forcing to isolate faults'],
      ['Diagnostikim i rrjetave fieldbus dhe i humbjes së komunikimit', 'Fieldbus diagnostics and loss-of-communication analysis'],
      ['Rikthim dhe dokumentim i programeve ekzistuese', 'Recovery and documentation of existing programs'],
      ['Verifikim i zinxhirit të sigurisë dhe i funksioneve mbrojtëse', 'Verification of the safety chain and protective functions'],
      ['Optimizim i sekuencave për të ulur kohën e ciklit', 'Sequence optimisation to reduce cycle time'],
    ],
  },
  {
    slug: 'plc-hmi-vfd', icon: 'panel', sort: 30,
    title_sq: 'Shërbime PLC, HMI dhe VFD',
    title_en: 'PLC, HMI and VFD services',
    summary_sq: 'Programim, parametrizim, backup dhe zëvendësim i pajisjeve të kontrollit.',
    summary_en: 'Programming, parameterisation, backup and replacement of control devices.',
    body_sq: 'Marrim përsipër ciklin e plotë të pajisjeve të kontrollit: nga zgjedhja e modelit të përshtatshëm dhe furnizimi, te programimi, vënia në punë dhe trajnimi i operatorëve. Për invertera kryejmë parametrizim sipas ngarkesës, rregullim rampash dhe mbrojtjesh, si dhe zëvendësim të njësive të vjetruara me modele aktuale duke ruajtur logjikën ekzistuese.',
    body_en: 'We take on the full lifecycle of control devices: from selecting the right model and supplying it, through programming, commissioning and operator training. For inverters we perform load-based parameterisation, ramp and protection tuning, and replacement of obsolete units with current models while preserving the existing logic.',
    points: [
      ['Programim PLC në TIA Portal, EcoStruxure, CX-One dhe GX Works', 'PLC programming in TIA Portal, EcoStruxure, CX-One and GX Works'],
      ['Dizajn dhe rindërtim ekranesh HMI në gjuhën shqipe', 'HMI screen design and rebuilds in Albanian'],
      ['Parametrizim VFD, autotuning motori dhe konfigurim komunikimi', 'VFD parameterisation, motor autotuning and communication setup'],
      ['Backup i programeve dhe arkivim i versioneve për çdo makinë', 'Program backup and version archiving for every machine'],
      ['Zëvendësim i pajisjeve të vjetruara me ekuivalentë aktualë', 'Replacement of obsolete devices with current equivalents'],
    ],
  },
  {
    slug: 'riparim-mekanik', icon: 'gear', sort: 40,
    title_sq: 'Riparim mekanik i makinerive',
    title_en: 'Mechanical machine repair',
    summary_sq: 'Ndërhyrje në transmisione, kushineta, boshte dhe grupe lëvizëse.',
    summary_en: 'Intervention on drives, bearings, shafts and moving assemblies.',
    body_sq: 'Zhurma, vibrimi dhe nxehtësia janë sinjale që një defekt mekanik po zhvillohet. Kryejmë demontim, matje dhe zëvendësim të kushinetave, guarnicioneve dhe elementëve të transmisionit, si dhe rreshtim boshtesh dhe rregullim tensioni rripash me instrumente të dedikuara.',
    body_en: 'Noise, vibration and heat are the signals that a mechanical failure is developing. We carry out dismantling, measurement and replacement of bearings, seals and transmission elements, plus shaft alignment and belt tensioning with dedicated instruments.',
    points: [
      ['Zëvendësim kushinetash me montim termik dhe kontroll tolerancash', 'Bearing replacement with thermal fitting and tolerance checks'],
      ['Rreshtim boshtesh me lazer dhe balancim rrotullues', 'Laser shaft alignment and rotating-assembly balancing'],
      ['Riparim reduktorësh, bashkuesish dhe grupesh transmisioni', 'Repair of gearboxes, couplings and drive assemblies'],
      ['Zëvendësim rripash e zinxhirësh me tensionim të matur', 'Belt and chain replacement with measured tensioning'],
      ['Punime saldimi dhe përpunimi për pjesë që nuk gjenden në treg', 'Welding and machining for parts no longer available'],
    ],
  },
  {
    slug: 'pneumatike-hidraulike', icon: 'cylinder', sort: 50,
    title_sq: 'Shërbime pneumatike dhe hidraulike',
    title_en: 'Pneumatic & hydraulic services',
    summary_sq: 'Riparim cilindrash, valvulash dhe njësish fuqie, plus kontroll rrjedhjesh.',
    summary_en: 'Repair of cylinders, valves and power units, plus leak surveys.',
    body_sq: 'Rrjedhjet e ajrit të komprimuar janë një nga humbjet më të mëdha e më të nënvlerësuara të energjisë në fabrikë. Kryejmë kontroll sistematik të rrjetit, riparim cilindrash me grupe guarnicionesh origjinale, pastrim dhe zëvendësim filtrash, si dhe analizë të vajit hidraulik.',
    body_en: 'Compressed-air leaks are one of the largest and most underestimated energy losses in a factory. We perform systematic network surveys, cylinder repairs with original seal kits, filter cleaning and replacement, and hydraulic oil analysis.',
    points: [
      ['Kontroll rrjedhjesh të ajrit dhe llogaritje e kursimit', 'Compressed-air leak surveys with savings calculation'],
      ['Riparim cilindrash pneumatikë e hidraulikë me guarnicione origjinale', 'Pneumatic and hydraulic cylinder repair with original seals'],
      ['Zëvendësim elementësh filtri dhe kontroll pastërtie vaji', 'Filter element replacement and oil cleanliness checks'],
      ['Prodhim zorrësh hidraulike sipas masës', 'Hydraulic hose assemblies made to measure'],
      ['Rregullim presionesh dhe njësish përgatitjeje ajri', 'Pressure setting and air preparation unit adjustment'],
    ],
  },
  {
    slug: 'mirembajtje-parandaluese', icon: 'shield', sort: 60,
    title_sq: 'Mirëmbajtje parandaluese',
    title_en: 'Preventive maintenance',
    summary_sq: 'Plane periodike inspektimi që parandalojnë ndalimet e paplanifikuara.',
    summary_en: 'Scheduled inspection plans that prevent unplanned downtime.',
    body_sq: 'Ndërtojmë një plan mirëmbajtjeje për çdo makinë kritike: çfarë kontrollohet, sa shpesh, me çfarë kriteri pranimi dhe cilat pjesë duhen mbajtur në magazinë. Vizitat periodike dokumentohen dhe trendi i matjeve ruhet, kështu që degradimi vihet re para se të bëhet defekt.',
    body_en: 'We build a maintenance plan for each critical machine: what gets checked, how often, against which acceptance criteria, and which parts should be held in store. Periodic visits are documented and measurement trends are retained, so degradation is noticed before it becomes a failure.',
    points: [
      ['Plan mirëmbajtjeje për çdo makinë me interval dhe kriter pranimi', 'Per-machine maintenance plan with intervals and acceptance criteria'],
      ['Inspektim termografik dhe matje vibrimi', 'Thermographic inspection and vibration measurement'],
      ['Lubrifikim i planifikuar me produktin e duhur për çdo pikë', 'Planned lubrication with the correct product per point'],
      ['Listë pjesësh kritike rezervë me nivele minimale stoku', 'Critical spare parts list with minimum stock levels'],
      ['Raport pas çdo vizite me gjetjet dhe veprimet e rekomanduara', 'Report after each visit with findings and recommended actions'],
    ],
  },
  {
    slug: 'modernizim', icon: 'upgrade', sort: 70,
    title_sq: 'Modernizim dhe retrofit',
    title_en: 'Modernisation & retrofit',
    summary_sq: 'Zgjatja e jetës së makinerive ekzistuese me kontroll dhe siguri moderne.',
    summary_en: 'Extending the life of existing machinery with modern control and safety.',
    body_sq: 'Shumë makineri në Kosovë dhe Shqipëri janë mekanikisht të shëndosha por elektrikisht të vjetruara, me pjesë komanduese që nuk prodhohen më. Retrofit-i zëvendëson vetëm pjesën e kontrollit: PLC dhe HMI të reja, drive modernë, siguri sipas standardeve aktuale — me një fraksion të kostos së një makine të re dhe pa ndryshuar procesin e prodhimit.',
    body_en: 'Many machines in Kosovo and Albania are mechanically sound but electrically obsolete, with control parts that are no longer manufactured. A retrofit replaces only the control portion: new PLC and HMI, modern drives, safety to current standards — at a fraction of the cost of a new machine and without changing the production process.',
    points: [
      ['Zëvendësim i PLC-ve të vjetruara duke ruajtur sekuencën ekzistuese', 'Replacement of obsolete PLCs while preserving the existing sequence'],
      ['Panele të reja komandimi sipas IEC 60204-1', 'New control panels to IEC 60204-1'],
      ['Përditësim i sistemit të sigurisë me vlerësim rreziku', 'Safety system upgrade with risk assessment'],
      ['Shtim i matjes së konsumit dhe i regjistrimit të prodhimit', 'Addition of consumption metering and production logging'],
      ['Dokumentacion i plotë teknik pas ndërhyrjes', 'Complete technical documentation after the work'],
    ],
  },
  {
    slug: 'menaxhim-pjesesh', icon: 'boxes', sort: 80,
    title_sq: 'Menaxhim i pjesëve kritike',
    title_en: 'Critical spare parts management',
    summary_sq: 'Identifikim, standardizim dhe furnizim i vazhdueshëm i pjesëve rezervë.',
    summary_en: 'Identification, standardisation and continuous supply of spare parts.',
    body_sq: 'Shpesh pjesa që ndalon linjën kushton pak — problemi është se askush nuk e di numrin e saj. Ne kalojmë nëpër makineritë tuaja, identifikojmë komponentët, ndërtojmë një listë pjesësh me numra dhe ekuivalentë, dhe përcaktojmë çfarë duhet mbajtur në magazinë e çfarë mund të porositet sipas nevojës.',
    body_en: 'Often the part that stops a line is inexpensive — the problem is that nobody knows its number. We walk your machines, identify the components, build a parts list with numbers and equivalents, and define what should be held in store versus ordered on demand.',
    points: [
      ['Inventarizim i komponentëve me foto dhe numra pjese', 'Component survey with photographs and part numbers'],
      ['Gjetje ekuivalentësh për pjesë të ndërprera nga prodhimi', 'Sourcing equivalents for discontinued parts'],
      ['Standardizim i markave për të ulur numrin e referencave', 'Brand standardisation to reduce the number of references'],
      ['Marrëveshje furnizimi me çmime dhe afate të fiksuara', 'Supply agreements with fixed prices and lead times'],
      ['Listë kritike e rishikuar çdo vit sipas historikut të defekteve', 'Critical list reviewed annually against failure history'],
    ],
  },
];
