/** Seed content: product categories and supplier brands. */

export const categories = [
  {
    slug: 'mekanike', icon: 'gear', sort: 10,
    name_sq: 'Pjesë mekanike', name_en: 'Mechanical parts',
    summary_sq: 'Kushineta, rripa, zinxhirë, bashkues, reduktorë dhe elementë transmisioni për linja prodhimi.',
    summary_en: 'Bearings, belts, chains, couplings, gearboxes and power-transmission elements for production lines.',
  },
  {
    slug: 'elektrike', icon: 'bolt', sort: 20,
    name_sq: 'Komponentë elektrikë', name_en: 'Electrical components',
    summary_sq: 'Kontaktorë, releta, çelësa mbrojtës, klema, ushqyes dhe aparaturë komanduese.',
    summary_en: 'Contactors, relays, protective switchgear, terminals, power supplies and control gear.',
  },
  {
    slug: 'automatizim', icon: 'cpu', sort: 30,
    name_sq: 'Automatizim dhe kontroll', name_en: 'Automation & control',
    summary_sq: 'PLC, HMI, module I/O, rele sigurie dhe komponentë për sisteme të automatizuara.',
    summary_en: 'PLCs, HMIs, I/O modules, safety relays and components for automated systems.',
  },
  {
    slug: 'pneumatike', icon: 'cylinder', sort: 40,
    name_sq: 'Pneumatikë', name_en: 'Pneumatics',
    summary_sq: 'Cilindra, elektrovalvula, njësi përgatitjeje ajri, rakorderi dhe tuba.',
    summary_en: 'Cylinders, solenoid valves, air preparation units, fittings and tubing.',
  },
  {
    slug: 'hidraulike', icon: 'droplet', sort: 50,
    name_sq: 'Hidraulikë', name_en: 'Hydraulics',
    summary_sq: 'Pompa, valvula drejtuese, filtra, cilindra, zorrë dhe elementë guarnicioni.',
    summary_en: 'Pumps, directional valves, filters, cylinders, hoses and sealing elements.',
  },
  {
    slug: 'sensore', icon: 'radar', sort: 60,
    name_sq: 'Sensorë dhe instrumentim', name_en: 'Sensors & instrumentation',
    summary_sq: 'Sensorë induktivë, fotoelektrikë, matje presioni, temperature, niveli dhe rrjedhjeje.',
    summary_en: 'Inductive and photoelectric sensors, pressure, temperature, level and flow measurement.',
  },
  {
    slug: 'motore-drive', icon: 'motor', sort: 70,
    name_sq: 'Motorë dhe drive', name_en: 'Motors & drives',
    summary_sq: 'Motorë elektrikë trefazorë, invertera frekuence, soft-starter dhe servo-sisteme.',
    summary_en: 'Three-phase electric motors, frequency inverters, soft starters and servo systems.',
  },
  {
    slug: 'kabllo', icon: 'cable', sort: 80,
    name_sq: 'Kabllo dhe lidhje', name_en: 'Cable & connectivity',
    summary_sq: 'Kabllo kontrolli e fuqie, kabllo fleksibël për zinxhir, konektorë M12 dhe aksesorë.',
    summary_en: 'Control and power cable, drag-chain cable, M12 connectors and accessories.',
  },
  {
    slug: 'panele', icon: 'cabinet', sort: 90,
    name_sq: 'Panele dhe ftohje', name_en: 'Enclosures & thermal',
    summary_sq: 'Armatura elektrike, ventilatorë me filtër, klimatizues panelesh dhe aksesorë montimi.',
    summary_en: 'Electrical enclosures, filter fans, panel coolers and mounting accessories.',
  },
  {
    slug: 'konsumabile', icon: 'drum', sort: 100,
    name_sq: 'Konsumabile industriale', name_en: 'Industrial consumables',
    summary_sq: 'Lubrifikantë, ngjitës industrialë, abrazivë, filtra, mjete pune dhe pajisje mbrojtëse.',
    summary_en: 'Lubricants, industrial adhesives, abrasives, filters, tooling and protective equipment.',
  },
];

export const brands = [
  { slug: 'siemens', name: 'Siemens', country: 'DE', is_featured: 1, sort: 10,
    summary_sq: 'SIMATIC PLC dhe HMI, SINAMICS drive, aparaturë SIRIUS.',
    summary_en: 'SIMATIC PLC and HMI, SINAMICS drives, SIRIUS control gear.' },
  { slug: 'schneider-electric', name: 'Schneider Electric', country: 'FR', is_featured: 1, sort: 20,
    summary_sq: 'TeSys, Altivar, Modicon dhe Harmony për komandim e mbrojtje.',
    summary_en: 'TeSys, Altivar, Modicon and Harmony control and protection.' },
  { slug: 'abb', name: 'ABB', country: 'CH', is_featured: 1, sort: 30,
    summary_sq: 'Kontaktorë AF, drive ACS dhe aparaturë modulare.',
    summary_en: 'AF contactors, ACS drives and modular switchgear.' },
  { slug: 'festo', name: 'Festo', country: 'DE', is_featured: 1, sort: 40,
    summary_sq: 'Cilindra, ishuj valvulash dhe përgatitje ajri.',
    summary_en: 'Cylinders, valve terminals and air preparation.' },
  { slug: 'smc', name: 'SMC', country: 'JP', is_featured: 1, sort: 50,
    summary_sq: 'Elektrovalvula, aktuatorë dhe komponentë pneumatikë.',
    summary_en: 'Solenoid valves, actuators and pneumatic components.' },
  { slug: 'skf', name: 'SKF', country: 'SE', is_featured: 1, sort: 60,
    summary_sq: 'Kushineta, njësi mbajtëse, guarnicione dhe lubrifikim.',
    summary_en: 'Bearings, housed units, seals and lubrication.' },
  { slug: 'omron', name: 'Omron', country: 'JP', is_featured: 1, sort: 70,
    summary_sq: 'Sensorë, rele, kontrollorë temperature dhe siguri.',
    summary_en: 'Sensors, relays, temperature controllers and safety.' },
  { slug: 'phoenix-contact', name: 'Phoenix Contact', country: 'DE', is_featured: 1, sort: 80,
    summary_sq: 'Klema, ushqyes QUINT, konektorë dhe mbrojtje mbitensioni.',
    summary_en: 'Terminal blocks, QUINT power supplies, connectors and surge protection.' },
  { slug: 'bosch-rexroth', name: 'Bosch Rexroth', country: 'DE', is_featured: 1, sort: 90,
    summary_sq: 'Hidraulikë industriale, valvula dhe teknologji lëvizjeje.',
    summary_en: 'Industrial hydraulics, valves and motion technology.' },
  { slug: 'sick', name: 'SICK', country: 'DE', is_featured: 1, sort: 100,
    summary_sq: 'Sensorë fotoelektrikë, barriera sigurie dhe enkoderë.',
    summary_en: 'Photoelectric sensors, safety light curtains and encoders.' },
  { slug: 'pilz', name: 'Pilz', country: 'DE', is_featured: 1, sort: 110,
    summary_sq: 'Rele sigurie PNOZ dhe kontrollorë të konfigurueshëm.',
    summary_en: 'PNOZ safety relays and configurable safety controllers.' },
  { slug: 'weidmuller', name: 'Weidmüller', country: 'DE', is_featured: 0, sort: 120,
    summary_sq: 'Klema, ndërfaqe rele dhe komponentë lidhjeje.',
    summary_en: 'Terminals, relay interfaces and connectivity components.' },
  { slug: 'ifm', name: 'ifm electronic', country: 'DE', is_featured: 0, sort: 130,
    summary_sq: 'Sensorë procesi, IO-Link dhe monitorim gjendjeje.',
    summary_en: 'Process sensors, IO-Link and condition monitoring.' },
  { slug: 'balluff', name: 'Balluff', country: 'DE', is_featured: 0, sort: 140,
    summary_sq: 'Sensorë induktivë, sisteme identifikimi dhe matje pozicioni.',
    summary_en: 'Inductive sensors, identification systems and position measurement.' },
  { slug: 'parker', name: 'Parker Hannifin', country: 'US', is_featured: 0, sort: 150,
    summary_sq: 'Filtrim hidraulik, rakorderi dhe sisteme lëvizjeje.',
    summary_en: 'Hydraulic filtration, fittings and motion systems.' },
  { slug: 'hydac', name: 'HYDAC', country: 'DE', is_featured: 0, sort: 160,
    summary_sq: 'Elementë filtri, akumulatorë dhe teknologji ftohjeje.',
    summary_en: 'Filter elements, accumulators and cooling technology.' },
  { slug: 'danfoss', name: 'Danfoss', country: 'DK', is_featured: 0, sort: 170,
    summary_sq: 'Invertera VLT dhe komponentë për kontroll lëvizjeje.',
    summary_en: 'VLT inverters and motion control components.' },
  { slug: 'mitsubishi-electric', name: 'Mitsubishi Electric', country: 'JP', is_featured: 0, sort: 180,
    summary_sq: 'Invertera FR, PLC MELSEC dhe HMI GOT.',
    summary_en: 'FR inverters, MELSEC PLCs and GOT HMIs.' },
  { slug: 'eaton', name: 'Eaton', country: 'IE', is_featured: 0, sort: 190,
    summary_sq: 'Mbrojtje motorike, aparaturë modulare dhe komandim.',
    summary_en: 'Motor protection, modular switchgear and control.' },
  { slug: 'weg', name: 'WEG', country: 'BR', is_featured: 0, sort: 200,
    summary_sq: 'Motorë trefazorë W22 dhe reduktorë.',
    summary_en: 'W22 three-phase motors and gear units.' },
  { slug: 'rittal', name: 'Rittal', country: 'DE', is_featured: 0, sort: 210,
    summary_sq: 'Armatura, ventilim dhe klimatizim panelesh.',
    summary_en: 'Enclosures, ventilation and panel climate control.' },
  { slug: 'lapp', name: 'LAPP', country: 'DE', is_featured: 0, sort: 220,
    summary_sq: 'Kabllo ÖLFLEX, UNITRONIC dhe presakabllo SKINTOP.',
    summary_en: 'ÖLFLEX and UNITRONIC cable, SKINTOP cable glands.' },
  { slug: 'gates', name: 'Gates', country: 'US', is_featured: 0, sort: 230,
    summary_sq: 'Rripa transmisioni, Poly Chain dhe zorrë hidraulike.',
    summary_en: 'Drive belts, Poly Chain and hydraulic hose.' },
  { slug: 'fag', name: 'FAG / Schaeffler', country: 'DE', is_featured: 0, sort: 240,
    summary_sq: 'Kushineta industriale dhe njësi mbajtëse.',
    summary_en: 'Industrial bearings and housed units.' },
  { slug: 'loctite', name: 'LOCTITE / Henkel', country: 'DE', is_featured: 0, sort: 250,
    summary_sq: 'Ngjitës anaerobikë, mbyllës filetash dhe riparim sipërfaqesh.',
    summary_en: 'Anaerobic adhesives, threadlockers and surface repair.' },
  { slug: 'klueber', name: 'Klüber Lubrication', country: 'DE', is_featured: 0, sort: 260,
    summary_sq: 'Vajra dhe graso speciale për industri ushqimore e të rëndë.',
    summary_en: 'Specialty oils and greases for food-grade and heavy industry.' },
  { slug: 'igus', name: 'igus', country: 'DE', is_featured: 0, sort: 270,
    summary_sq: 'Zinxhirë kabllosh, kabllo chainflex dhe kushineta polimer.',
    summary_en: 'Cable carriers, chainflex cable and polymer bearings.' },
  { slug: 'schmersal', name: 'Schmersal', country: 'DE', is_featured: 0, sort: 280,
    summary_sq: 'Çelësa sigurie, bllokues dere dhe komponentë mbrojtës.',
    summary_en: 'Safety switches, door interlocks and guarding components.' },
];
